version: '3.7'
services:

  dbchallenge:
    container_name: dbchallenge
    image: postgres:alpine3.16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=challenge
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - challege      

volumes:
  db-volume:

networks:
    challege: